use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

use sha2::{Digest, Sha256};

fn main() {
    tauri_build::build();

    // Hash each bundled SKILL.md and emit a generated module so the runtime
    // can verify the bytes match what the build saw.
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let skills_dir = manifest_dir.join("resources").join("skills");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_path = out_dir.join("skill_hashes.rs");

    let mut entries: Vec<(String, String)> = Vec::new();

    if skills_dir.exists() {
        // Re-run if a skill is added/removed at the directory level.
        println!("cargo:rerun-if-changed={}", skills_dir.display());
        for entry in fs::read_dir(&skills_dir).expect("read skills dir") {
            let entry = entry.expect("read skill dir entry");
            if !entry.path().is_dir() {
                continue;
            }
            let skill_md = entry.path().join("SKILL.md");
            if !skill_md.exists() {
                continue;
            }
            let bytes = fs::read(&skill_md).expect("read SKILL.md");
            let hash = format!("{:x}", Sha256::digest(&bytes));
            let name = entry.file_name().to_string_lossy().into_owned();
            entries.push((name, hash));
            // Tell cargo to re-run the build if SKILL.md changes.
            println!("cargo:rerun-if-changed={}", skill_md.display());
        }
    }

    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut f = fs::File::create(&out_path).expect("create skill_hashes.rs");
    writeln!(f, "// Generated by build.rs — do not edit.").unwrap();
    writeln!(f, "pub const SKILL_HASHES: &[(&str, &str)] = &[").unwrap();
    for (name, hash) in &entries {
        writeln!(f, "    ({:?}, {:?}),", name, hash).unwrap();
    }
    writeln!(f, "];").unwrap();
}
